### ISSUE TITLE
No bfsSolver() in its MaximumSubRectDivision.h

### ISSUE THREAD

**Issue by ghost** [CourierLo/TMSTC-Star#1]
Platform: VM Ubuntu 18.04

HI Courier, I am trying to run your algorithm. However, there is a "bfsSolver" function used in MSRD.cpp, and it doesn't have a corresponding definition in MSRD.h file. 

I have tried to add a "bfsSolver" in the header, and it indeed helped me launch the package. But there was no response in RViz window, and the map_transformer terminal returned "Failed to get ROS planning path".

Any errors with it? Thx

**Comment by ychen441** [comment]
Debugged

**Comment by ghost** [comment]
Debugged
